---
tap_install:
  values:
    profile: view
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    shared:
      ingress_domain: "view.tap-demo.coraiberkleid.net"
      ingress_issuer: ""

    contour:
      envoy:
        service:
          type: LoadBalancer # NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing.

    tap_gui:
      ingressEnabled: true
      service_type: ClusterIP
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/ciberkleid-tap/tap-catalog/blob/main/catalog-info.yaml
            - type: url
              target: https://github.com/ciberkleid-tap/yelb-catalog/blob/main/catalog-info.yaml
            - type: url
              target: https://github.com/ciberkleid-tap/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml

        # kubernetes:
        #   serviceLocatorMethod:
        #     type: 'multiTenant'
        #   clusterLocatorMethods:
        #     - type: 'config'
        #       clusters:
        #         - url: CLUSTER-URL
        #           name: CLUSTER-NAME # Build profile cluster can go here.
        #           authProvider: serviceAccount
        #           serviceAccountToken: CLUSTER-TOKEN
        #           skipTLSVerify: TRUE-OR-FALSE-VALUE
        #         - url: CLUSTER-URL
        #           name: CLUSTER-NAME # Run profile cluster can go here.
        #           authProvider: serviceAccount
        #           serviceAccountToken: CLUSTER-TOKEN
        #           skipTLSVerify: TRUE-OR-FALSE-VALUE

    appliveview:
      ingressEnabled: true

  # Might need to tell GUI to access Grype metadata store on build cluster
