---
tap_install:
  values:
    profile: view
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    shared:
      ingress_domain: "view.tap-demo.coraiberkleid.net"
      ingress_issuer: ""
      #ingress_issuer: letsencrypt-production

    contour:
      envoy:
        service:
          type: LoadBalancer # NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing.

    tap_gui:
      ingressEnabled: true
      service_type: ClusterIP
      # tls:
      #   namespace: cert-manager
      #   secretName: tap-gui
      tls:
        namespace: contour-tls
        secretName: tls
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/ciberkleid-tap/tap-catalog/blob/main/catalog-info.yaml
            - type: url
              target: https://github.com/ciberkleid-tap/yelb-catalog/blob/main/catalog-info.yaml
            - type: url
              target: https://github.com/ciberkleid-tap/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml

        # kubernetes:
        # See tap-sensitive-values.sops.yaml

    appliveview:
      ingressEnabled: true
    
    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: contour-tls
        secret_name: tls

  # Might need to tell GUI to access Grype metadata store on build cluster
