apiVersion: ENC[AES256_GCM,data:lHg=,iv:wdATeOf4pXqqgzM3NXKibVPIuJE0VjYP+zLF1YPfjU8=,tag:z9jL2uqOzOpoTacxiOgPVQ==,type:str]
kind: ENC[AES256_GCM,data:3ddUIFsR,iv:diiXEqaMri/Qa1DgXQCs7SL061tVnVo4whZ12nVb9Us=,tag:5a3sy9wemHQMAVlNU3x91w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VoudFHDF6cQN,iv:tx6hcvpWxm9vW2vAmuXkBj+hSMaeknVsMPuasKKhpcA=,tag:kpZqwjf8KayePwvPRmrl6w==,type:str]
    namespace: ENC[AES256_GCM,data:NxWd0TdybZm24tk=,iv:pflQhZPg19ebx5Scs1gQTgaEXFCYquwlwO+58Eq6z6w=,tag:JNM+zd9N63JItaXadrAz3A==,type:str]
type: ENC[AES256_GCM,data:zAh92Ycg,iv:mEj6L+hJmddakZtWBi3vUWgV5KsA99RO0XqflowEzag=,tag:gE64io/xKIaYBx0pf6smQQ==,type:str]
stringData:
    content.yaml: ENC[AES256_GCM,data:ZzD/jM8Ufm1hHGxUsS3gHDc2RnCNOfLKodJgKjmpR3+vy8PyIFI8sNYpr3H83UxVFv1BKl/5mxr6Zl+4v1UO7/pZ0HkZmmWpIU6z9l4dGGRPIIxpDmK1KLSwcnZ3A/TIFzdHC0eBDA==,iv:tESaFDl3+5jdEB5+GAavq1bsvFx/cv1QrXxcsOxzG2c=,tag:p9P+7S/wyRCiFl04oe6tIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n3639jatjacu4j86223ajca05z5tg4f75v0kmtn7q23v3l6lladq08y4jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVBXcWxuclViVzRIblVK
            d1Bna0xhQnU5MVVrbEx4LzNLclI4WlcwNlg4CmZUMUNFL1o3S0tPZCtWVkUxeU8r
            d2hxZEZwOUdqNC8yYWgzekhHTlRUU28KLS0tIE45c0pBRDc0Vk5IRzgvU00zMEVE
            dlhzbmIzR0p2Z0JMMmN2Vk0zdHpIelUKo2PfvG0TNnY1s1xPsxee3AjO/4Y0mzEM
            IjieT/AkJBKwHre7S4FkXeS371hah899PzRIym60p0TMZZ3L0Vyngg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T17:56:21Z"
    mac: ENC[AES256_GCM,data:usj/v2GKdKhN6V2FLkCjYmM4Y09WTE6pNRkHI2sYKSkUj+xh+3TxHkAbGC/DKMXqiongvs6UbKVAU8L+DtbChBQPiu3jnI2GsnvwSNE1KGkHfbmwUiBPHnCeHIhSdzw1B7RQ3lDdB82gN5ZDYa3iiemercOQLrb348X4x+Q0vYA=,iv:LYQE7SYZ622LX3j7PouYWba8Fx02njvd4MTrJT3n/44=,tag:Ew7Wcr55i/07TI3hK4fo9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
