apiVersion: ENC[AES256_GCM,data:lHg=,iv:wdATeOf4pXqqgzM3NXKibVPIuJE0VjYP+zLF1YPfjU8=,tag:z9jL2uqOzOpoTacxiOgPVQ==,type:str]
kind: ENC[AES256_GCM,data:3ddUIFsR,iv:diiXEqaMri/Qa1DgXQCs7SL061tVnVo4whZ12nVb9Us=,tag:5a3sy9wemHQMAVlNU3x91w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VoudFHDF6cQN,iv:tx6hcvpWxm9vW2vAmuXkBj+hSMaeknVsMPuasKKhpcA=,tag:kpZqwjf8KayePwvPRmrl6w==,type:str]
    namespace: ENC[AES256_GCM,data:NxWd0TdybZm24tk=,iv:pflQhZPg19ebx5Scs1gQTgaEXFCYquwlwO+58Eq6z6w=,tag:JNM+zd9N63JItaXadrAz3A==,type:str]
type: ENC[AES256_GCM,data:zAh92Ycg,iv:mEj6L+hJmddakZtWBi3vUWgV5KsA99RO0XqflowEzag=,tag:gE64io/xKIaYBx0pf6smQQ==,type:str]
stringData:
    content.yaml: ENC[AES256_GCM,data:SknHTr8opVOzM3cV04KCpqLO6/T57KBooD2Pjes9SS+8xyZ2DF92umwGLt5D3NV0q207soezDG3LY+/lW0PTpvYGMe1F1/EkDX4YUGE56g5a8xlQ66F+1GYgXaRbA6vVN4q/DCxeEQ==,iv:E8fyqHYGR8636t6B0CYOleyJXkSDIeHP78wLHiWPmuE=,tag:7ziQqUUiyRpEyjGjznKlfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n3639jatjacu4j86223ajca05z5tg4f75v0kmtn7q23v3l6lladq08y4jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVBXcWxuclViVzRIblVK
            d1Bna0xhQnU5MVVrbEx4LzNLclI4WlcwNlg4CmZUMUNFL1o3S0tPZCtWVkUxeU8r
            d2hxZEZwOUdqNC8yYWgzekhHTlRUU28KLS0tIE45c0pBRDc0Vk5IRzgvU00zMEVE
            dlhzbmIzR0p2Z0JMMmN2Vk0zdHpIelUKo2PfvG0TNnY1s1xPsxee3AjO/4Y0mzEM
            IjieT/AkJBKwHre7S4FkXeS371hah899PzRIym60p0TMZZ3L0Vyngg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T13:45:12Z"
    mac: ENC[AES256_GCM,data:D1tGcqe8I2WawUvr4mBYE5x7M/+S6ij1vsBF3Q7CbzAhU2hAmS9GvW3jhC1NUlJvcQYLHKX4E0bdjCawqBnHJ1av/+s0bhMw5UfmQvxaohKYy10hWDT2v0NHlU5YCldpYP1P8LOLA+dREPKkDE2429KqYvx+wkq+C9YknFEPIlI=,iv:KwmRtlz2htFIVGuZS/ASnq6P5rmDsimyAoqzRwOztsg=,tag:xoI+fbu2e05r1DLgpQvB6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
