apiVersion: ENC[AES256_GCM,data:nuo=,iv:9FB7e6AyNjLndC/BuVQAAa46KrfaMx8aN3GBCK4wWMA=,tag:z5Tb7WJFKbx1QK5I5P2ccw==,type:str]
kind: ENC[AES256_GCM,data:cJPT4icy,iv:jTN2HtsKqVNhByCi0H9XH6PhJRvfg0EGoL8m/R04vaU=,tag:BEroiIoft3jDl1Glzy3/Fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nw1nBy0Txb+FnGbavfz9mKyZp7Y=,iv:sgQLBavPmy7f26sAJ3Gp7keMybB+HjlfpDM88VV457M=,tag:e2F0AVLYF6sxqtoC2r0+VA==,type:str]
    namespace: ENC[AES256_GCM,data:iQvK50ldHBocXNY=,iv:d/jwMKkyyhpvLZR41M962g3unWruiPA9MokIBEHDEb8=,tag:Ir+233pilNQL8UDp4/aAhg==,type:str]
type: ENC[AES256_GCM,data:SpsE0L8S,iv:l/7u1cYwE48jnXgLd9d9CYK6sDbkx5DcqP72vD8w7hs=,tag:grsPskdCr9AWzp2fdVdcAA==,type:str]
stringData:
    content.yaml: ENC[AES256_GCM,data:p4F8WkCiKRqk6yXJmXu4/u1U/v3lf7HlBSfcLjQzHLgNDJVSrORAZhaIYDv3+spoeBaqt0l5uyHN+Xa8cu5u5n9kL9izRqIoqdYG3VKQeGW6gEaNSuupOiYmOBGsyL1X5SygqXreGA==,iv:0AncWLkUgTmjtx5D4prjfcJyPiVCnPTO9DEaByfqKq8=,tag:cQtvy/p2LyTxaFhPTX//nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n3639jatjacu4j86223ajca05z5tg4f75v0kmtn7q23v3l6lladq08y4jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS3RMTWJVZTlWUGVXQUFq
            Q1Y5L3JwNGdsd2JvNkJ4b2xmT3hxbW44bm5FCi9WM3hjaHlyMVROdk4xV2NFbjBN
            cWl5amRvSXl2UDlZZUdWSEtwRTFrSk0KLS0tIE5aRlRESEcrd2JnbWVzcEpPNWpa
            dHR1Yk1haU16V09ubDdwejZsaUpMS0UKtoJMcQm824T/oR347UoDFVQ8CxJ3FP8r
            Ib3E0mrHkgBgpTRZXNa5efR33xK3vyGiDjEsVqjS5EPD4vdU7dtkjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T14:07:08Z"
    mac: ENC[AES256_GCM,data:Hx0bMsHt49jRlQmCYmjpyC6Pwaz2c6OMo9bJq5upIQMRy2fGzKf8/FvVAvARwHGS74bTSXJOdWdB9ejf7ogrW3E9bLjU3YcXebrE5S10wZH8QIMMobf38NczyohLjkJp3O1xMyyPoDqp44jcHCphvxq7eAGzFII8xGMCRlkKxQA=,iv:QRxi7g/qTE0ixYWeupQ5Jc3kvOyt/6JEJVTGXbQ70b4=,tag:Hl0cbFpzm65bPehz4bIf8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
