---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    shared:
      ingress_domain: "build.tap-demo.coraiberkleid.net"
      ingress_issuer: ""
      image_registry:
        project_path: "us-central1-docker.pkg.dev/fe-ciberkleid/tap-demo" # To be used by Build Service by appending "/buildservice" and used by Supply chain by appending "/workloads".

    # The above shared keys can be overridden in the below section.

    buildservice:
    # Takes the value from the shared section by default, but can be overridden by setting a different value.
      # kp_default_repository: "KP-DEFAULT-REPO"
      # kp_default_repository_secret:
      #   name: "KP-DEFAULT-REPO-SECRET"
      #   namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning: # Optional if the corresponding shared keys are provided.
      # registry:
      #   server: "SERVER-NAME"
      #   repository: "REPO-NAME"
      gitops:
        ssh_secret: "git-ssh" # (Optional) Defaults to "".
    grype:
      namespace: "default" # (Optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"
    scanning:
      metadataStore: 
        url: "" # Deactivate the Supply Chain Security Tools - Store integration.
