apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: spring-cloud-gateway
  namespace: tap-install
  # annotations:
  #   kapp.k14s.io/change-group: pkgi
  #   kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
  #   kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
    versionSelection:
      constraints: 2.0.2
  values:
    - secretRef:
        name: tap-values
    - secretRef:
        name: tap-sensitive-values
