tap_install:
    sensitive_values: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n3639jatjacu4j86223ajca05z5tg4f75v0kmtn7q23v3l6lladq08y4jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaWJTcERRcnRsb1hQbStJ
            VHZ1NnZUR1dmSDBzNE9KSXdzSk5lVTBndUhFCkhYUlNYK1dSUXU2QkI3U0ZvREdw
            ZmJheXhSYzdyZUt1b3NIV0JsTXRxUDAKLS0tIHhpcDVFbmxDMk16Q2tyaEplQXov
            Z2V4MDBCdFRBVlEwTmZmSXB3WUJnQnMKb3WGdegXmYdUsjawDUISd9HfYCeXdOt7
            acQOo93E8B6AjQvHJytxVKWWFgLomJ/OqzhAtvFWTPz+mu7CKyTcPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T22:57:15Z"
    mac: ENC[AES256_GCM,data:HL9iNE4rdRqepfIyo7bDhn7FAnlWW4sSHer2uDXW3FgiUza30iW8HiyphfYtE5gf7V/RLQjdQSkEXngbDHR9JnrYmUldq93kva+0XfBFDYKerghiGJfJ/YMpU2SgGNEUvXH+2OuhhZ/0cyKAz+ZOFyZleCb0uoHs948r+d+dqH8=,iv:9BHIH5AsE/ulMH2mzR8rgfv0xJL32zSdIeHOEdRZbHc=,tag:CIVB8jjJTg4/aleXb2ZuRA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
